# Generated by Django 4.0.3 on 2022-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_table', to='core.restaurant_table'),
        ),
    ]
